name: "Tâche"
description: "Créer une tâche de travail"
title: "Tâche: "
labels: []
assignees: []

body:
  - type: textarea
    id: goal
    attributes:
      label: "Objectif"
      description: "Qu’est-ce qu’on veut obtenir ?"
      placeholder: "Décrire le résultat attendu."
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Contexte"
      description: "Pourquoi / pour qui / liens utiles."
      placeholder: "Contexte, contraintes, références."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Découpage en étapes."
      options:
        - label: "À définir"
    validations:
      required: false

  - type: textarea
    id: acceptance
    attributes:
      label: "Critères d’acceptation"
      description: "Comment on sait que c’est terminé ?"
      placeholder: "- …\n- …"
    validations:
      required: false
