name: "Tâche"
description: "Template générique pour créer une tâche"
title: "Tâche: "
labels: []
assignees: []

body:
  - type: markdown
    attributes:
      value: "Merci de remplir les informations ci-dessous."

  - type: input
    id: summary
    attributes:
      label: "Résumé"
      description: "Une phrase pour décrire le travail à faire."
      placeholder: "Ex: Ajouter une CI GitHub Actions"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "Détails"
      description: "Contexte, contraintes, liens utiles, etc."
      placeholder: "Décris le besoin et les contraintes."
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      description: "Éléments à réaliser."
      options:
        - label: "Lint"
        - label: "Prettier"
